[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bricks2marble"
version = "0.0.5"
authors = [
  { name="Richard Krieg", email="irkri@irkri.net" },
  { name="Lars Gabriel", email="lgabriel23@gmx.de" },
  { name="Mario Stanke", email="mario.stanke@uni-greifswald.de" },
]
description = "Pre- and postprocessing tools for genome annotation."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
dependencies = ["numpy", "pydantic"]

[project.optional-dependencies]
tf = ["hidten[tensorflow]"]
plot = ["plotly"]

[project.urls]
Homepage = "https://github.com/gaius-augustus/bricks2marble"
Issues = "https://github.com/gaius-augustus/bricks2marble/issues"