import random
import re
import string
import subprocess
from collections.abc import Sequence
from pathlib import Path
from typing import overload

import plotly.express as px
from plotly import graph_objects as go
from plotly.subplots import make_subplots
from plotly.validator_cache import ValidatorCache
from pydantic import BaseModel, ValidationError

from ..struct import Annotation


class CompareMetrics(BaseModel):

    sensitivity: float
    precision: float

    missed: float | None = None
    novel: float | None = None

    @property
    def F1(self) -> float:
        if self.precision == 0 or self.sensitivity == 0:
            return 0
        return (
            2 * self.precision * self.sensitivity
            / (self.precision + self.sensitivity)
        )


class AnnotationComparison(BaseModel):

    base: CompareMetrics
    exon: CompareMetrics
    intron: CompareMetrics
    intron_chain: CompareMetrics
    transcript: CompareMetrics
    locus: CompareMetrics


@overload
def compare_gtf(
    annotation: Annotation | Path | str,
    reference: Annotation | Path | str,
    gffcompare: Path | str | None = ...,
    e: int = ...,
) -> AnnotationComparison:
    ...
@overload
def compare_gtf(
    annotation: list[Annotation | Path | str],
    reference: Annotation | Path | str,
    gffcompare: Path | str | None = ...,
    e: int = ...,
) -> list[AnnotationComparison]:
    ...
def compare_gtf(
    annotation: Annotation | Path | str | list[Annotation | Path | str],
    reference: Annotation | Path | str,
    gffcompare: Path | str | None = None,
    e: int = 0,
) -> AnnotationComparison | list[AnnotationComparison]:
    """Compare two annotation with the tool gffcompare:
    https://github.com/gpertea/gffcompare

    The result is an easily accessible collection of metrics returned by
    this program.
    All files generated by gffcompare are immediately deleted after
    processing.

    Args:
        annotation (Annotation or Path): The annotation you want to
            compare to the reference. If an
            :class:`~bricks2marble.struct.annotation.Annotation` is
            given, this will be converted to a gtf file first with the
            `.to_gtf()` method. You can also supply a sequence of
            annotations, each of which are then compared to the
            reference and metrics for all of these comparisons are
            returned.
        reference (Annotation or Path): The reference annotation. If an
            :class:`~bricks2marble.struct.annotation.Annotation` is
            given, this will be converted to a gtf file first with the
            `.to_gtf()` method.
        gffcompare (Path, optional): Path to the executable gffcompare.
            Defaults to just 'gffcompare', if it is properly added to
            the path.
        e (int, optional): Option `e` of `gffcompare`. Maximum allowed
            range of terminal exons in reference transcripts. Defaults
            to 0.

    Returns:
        AnnotationComparison: See
            :class:`bricks2marble.tools.gtf.AnnotationComparison`. If a
            sequence of annotations is given, instead is a sequence of
            comparisons.
    """
    seq_given = True
    if not isinstance(annotation, list):
        annotation = [annotation]
        seq_given = False

    for i in range(len(annotation)):
        if isinstance(annotation[i], str):
            annotation[i] = Path(annotation[i]).expanduser()
    if isinstance(reference, str): reference = Path(reference).expanduser()
    if isinstance(gffcompare, Path | str):
        gffcompare = str(Path(gffcompare).expanduser())
    elif gffcompare is None:
        gffcompare = "gffcompare"

    random_id = "".join(
        random.choices(string.ascii_uppercase + string.digits, k=10)
    )
    cache_dir = Path.cwd() / f"_cache_{random_id}/"
    cache_dir.mkdir(exist_ok=True)

    for i in range(len(annotation)):
        if isinstance(annotation[i], Annotation):
            annotation[i].to_gtf(cache_dir / f"annotation_{i}.gtf")
            annotation[i] = cache_dir / f"annotation_{i}.gtf"
    if isinstance(reference, Annotation):
        reference.to_gtf(cache_dir / "reference.gtf")
        reference = cache_dir / "reference.gtf"

    results = []
    for i in range(len(annotation)):
        subprocess.run([
            f"{gffcompare}",
            "--strict-match",
            f"-e {e}",
            "-T",
            "-o",
            str(cache_dir) + ("/" if not str(cache_dir).endswith("/") else ""),
            "-r",
            str(reference),
            str(annotation[i]),
        ], check=True, stderr=subprocess.DEVNULL)

        pattern = re.compile(
            r'^\s*(.+?) level:\s+([\d.]+|-nan)\s+\|\s+([\d.]+|-nan)'
        )
        pattern_mn = re.compile(
            r'^\s*(Missed|Novel) (.+?):[\s/\d.]+\(\s*([\d.]+)%\)'
        )

        results.append({})
        with open(cache_dir / ".stats", 'r', encoding='utf-8') as file:
            for line in file.readlines():
                match = pattern.match(line)
                match_mn = pattern_mn.match(line)
                if match is not None:
                    level = match.group(1).strip().lower().replace(" ", "_")
                    sensitivity = float(match.group(2))
                    if match.group(3) == "-nan":
                        precision = 0
                    else:
                        precision = float(match.group(3))
                    results[-1][level] = {
                        'sensitivity': sensitivity / 100,
                        'precision': precision / 100,
                    }
                if match_mn is not None:
                    level = match_mn.group(2).strip()[:-1]
                    if level == "loc": level = "locus"
                    mn = match_mn.group(1).lower()
                    perc = float(match_mn.group(3))
                    results[-1][level] = results[-1][level] | {
                        mn: round(perc / 100, 3),
                    }

    for name in cache_dir.iterdir():
        (cache_dir / name).unlink()
    if not any(cache_dir.iterdir()):
        cache_dir.rmdir()

    try:
        if seq_given:
            return [AnnotationComparison(**result) for result in results]
        else:
            return AnnotationComparison(**results[0])
    except ValidationError:
        return AnnotationComparison(
            base=CompareMetrics(sensitivity=0, precision=0),
            exon=CompareMetrics(sensitivity=0, precision=0),
            intron=CompareMetrics(sensitivity=0, precision=0),
            intron_chain=CompareMetrics(sensitivity=0, precision=0),
            transcript=CompareMetrics(sensitivity=0, precision=0),
            locus=CompareMetrics(sensitivity=0, precision=0),
        )


def annotation_diff(
    annotation1: Annotation,
    annotation2: Annotation,
) -> Annotation:
    """Creates a diff of two annotations. Returns a new annotation that
    contains all transcripts that are not in both given annotations.
    """
    annotation = Annotation()
    for gene1 in annotation1:
        for gene2 in annotation2:
            if (
                gene1.seqname == gene2.seqname
                and gene1.strand == gene2.strand
                and gene1.start == gene2.start
                and gene1.end == gene2.end
            ): break
        else: # no break
            for tx in gene1:
                for entry in tx.entries:
                    g_id = entry.attribute("gene_id")
                    t_id = entry.attribute("transcript_id")
                    entry.attributes = (
                        f"gene_id \"left_{g_id}\"; "
                        f"transcript_id \"left_{t_id}\";"
                    )
                    annotation.add(entry)

    for gene2 in annotation2:
        for gene1 in annotation1:
            if (
                gene1.seqname == gene2.seqname
                and gene1.strand == gene2.strand
                and gene1.start == gene2.start
                and gene1.end == gene2.end
            ): break
        else: # no break
            for tx in gene2:
                for entry in tx.entries:
                    g_id = entry.attribute("gene_id")
                    t_id = entry.attribute("transcript_id")
                    entry.attributes = (
                        f"gene_id \"right_{g_id}\"; "
                        f"transcript_id \"right_{t_id}\";"
                    )
                    annotation.add(entry)
    return annotation


def annotation_and(
    annotation1: Annotation,
    annotation2: Annotation,
) -> Annotation:
    """Returns a new annotation that contains all transcripts that are
    unanimous in both given annotations.
    """
    annotation = Annotation()
    for gene1 in annotation1:
        for gene2 in annotation2:
            if (
                gene1.seqname == gene2.seqname
                and gene1.strand == gene2.strand
                and gene1.start == gene2.start
                and gene1.end == gene2.end
            ):
                for tx in gene1:
                    for entry in tx.entries:
                        annotation.add(entry)
    return annotation


def annotation_or(
    annotation1: Annotation,
    annotation2: Annotation,
) -> Annotation:
    """Returns a new annotation that contains all transcripts of both
    given annotations.
    """
    annotation = Annotation()
    for gene1 in annotation1:
        for tx in gene1:
            for entry in tx.entries:
                g_id = entry.attribute("gene_id")
                t_id = entry.attribute("transcript_id")
                entry.attributes = (
                    f"gene_id \"left_{g_id}\"; "
                    f"transcript_id \"left_{t_id}\";"
                )
                annotation.add(entry)

    for gene2 in annotation2:
        exists = False
        for gene in annotation:
            if (
                gene.seqname == gene2.seqname
                and gene.strand == gene2.strand
                and gene.start > gene2.start
            ):
                # overshot, is not there yet
                break
            if (
                gene.seqname == gene2.seqname
                and gene.strand == gene2.strand
                and gene.start == gene2.start
                and gene.end == gene2.end
            ):
                exists = True
                break
        if not exists:
            for tx in gene2:
                for entry in tx.entries:
                    g_id = entry.attribute("gene_id")
                    t_id = entry.attribute("transcript_id")
                    entry.attributes = (
                        f"gene_id \"right_{g_id}\"; "
                        f"transcript_id \"right_{t_id}\";"
                    )
                    annotation.add(entry)
    return annotation


def hex_to_rgba(hex_color: str, alpha: float = 0.5) -> str:
    hex_color = hex_color.lstrip("#")
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)
    return f"rgba({r},{g},{b},{alpha})"


def plot_comparison(
    metrics: Sequence[AnnotationComparison],
    labels: Sequence[str] | None = None,
    zoom: bool = False,
    flip_axes: bool = False,
    missing_novel: bool = False,
    table: bool = False,
) -> go.Figure:
    keys = ["base", "intron", "transcript", "exon", "intron_chain", "locus"]
    fig = make_subplots(
        rows=2 + (1 if missing_novel else 0) + (1 if table else 0),
        cols=3,
        subplot_titles=[
            key[0].upper()+key[1:].replace("_", "-") for key in keys
        ]
        + (
            ["Percentage of novel and missing features"]
            if missing_novel else []
        )
        + (
            ["Metrics (Sensitivity | Precision (F1))"] if table else []
        ),
        specs=[
            [{'type': 'scatter'}, {'type': 'scatter'}, {'type': 'scatter'}],
            [{'type': 'scatter'}, {'type': 'scatter'}, {'type': 'scatter'}],
        ]
        + ([
            [{'type': 'bar', 'colspan': 3}, None, None],
        ] if missing_novel else [])
        + ([
            [{'type': 'table', 'colspan': 3}, None, None],
        ] if table else []),
        horizontal_spacing=0.05,
        vertical_spacing=0.1,
    )
    if labels is None:
        labels = [f"Model {i+1}" for i in range(len(metrics))]

    SymbolValidator = ValidatorCache.get_validator("scatter.marker", "symbol")
    raw_symbols = SymbolValidator.values[2:19*12:12]
    colors = px.colors.qualitative.Plotly

    if table:
        table_rows = [[] for _ in range(len(keys))]
        color_cols = [[] for _ in range(len(keys))]
    for i, metric in enumerate(metrics):
        for j, key in enumerate(keys):
            row = j // 3 + 1
            col = j % 3 + 1
            x, y, f1 = (
                getattr(metric, key).sensitivity,
                getattr(metric, key).precision,
                getattr(metric, key).F1,
            )
            if table: table_rows[j].append(
                f"<b>{x:.3f} | {y:.3f}<br>    ({f1:.3f})</b>"
            )
            if table: color_cols[j].append(hex_to_rgba(colors[i], alpha=0.5))
            if flip_axes:
                x, y = y, x

            hover_text = [
                f"{key[0].upper()+key[1:].replace('_', '-')}"
                f"<br>Sensitivity: {x:.3f}<br>Precision: {y:.3f}"
                f"<br>F1: {f1:.3f}"
            ]
            fig.add_trace(go.Scatter(
                x=[x],
                y=[y],
                name=labels[i],
                marker=dict(
                    symbol=raw_symbols[i%10],
                    color=colors[i],
                    size=8,
                ),
                showlegend=j==0,
                legendgroup=f"group {i}",
                text=hover_text,
                hoverinfo="text"
            ), row=row, col=col)

            missed = getattr(getattr(metric, key), "missed", None)
            novel = getattr(getattr(metric, key), "novel", None)
            if missing_novel and missed is not None and novel is not None:
                fig.add_trace(go.Bar(
                    x=[key, key],
                    y=[-missed, novel],
                    name=labels[i],
                    marker_color=colors[i],
                    showlegend=False,
                    legendgroup=f"group {i}",
                ), row=3, col=1)

    if table:
        fig.add_trace(go.Table(
            header=dict(
                values=[
                    key[0].upper()+key[1:].replace('_', '-') for key in keys
                ],
                align="center",
                font=dict(size=14),
            ),
            cells=dict(
                values=table_rows,
                fill_color=color_cols,
                align="center",
            ),
        ), row=4 if missing_novel else 3, col=1)


    for j, key in enumerate(keys):
        row = j // 3 + 1
        col = j % 3 + 1
        fig.update_xaxes(
            range=[0, 1] if not zoom else None,
            scaleanchor=f'y{j+1}' if not zoom else None,
            constrain='domain',
            row=row,
            col=col,
            dtick=.1 if not zoom else None,
        )
        fig.update_yaxes(
            range=[0, 1] if not zoom else None,
            constrain='domain',
            row=row,
            col=col,
            dtick=.1 if not zoom else None,
        )

        fig.add_annotation(
            text="Sensitivity" if not flip_axes else "Precision",
            xref=f"x{j+1}", yref=f"y{j+1}",
            x=1.0, y=0,
            showarrow=False,
            font=dict(size=14),
            opacity=0.5,
            xanchor="right", yanchor="bottom",
        )
        fig.add_annotation(
            text="Precision" if not flip_axes else "Sensitivity",
            xref=f"x{j+1}", yref=f"y{j+1}",
            x=0, y=1.0,
            showarrow=False,
            font=dict(size=14),
            opacity=0.5,
            textangle=-90,
            xanchor="left", yanchor="top",
        )

    if missing_novel:
        fig.add_annotation(
            text="Novel",
            xref="paper", yref="y7",
            x=0.05, y=0.5,
            showarrow=False,
            font=dict(size=14),
            opacity=0.5,
            textangle=-90,
            xanchor="left", yanchor="middle",
        )
        fig.add_annotation(
            text="Missed",
            xref="paper", yref="y7",
            x=0.05, y=-0.5,
            showarrow=False,
            font=dict(size=14),
            opacity=0.5,
            textangle=-90,
            xanchor="left", yanchor="middle",
        )

    fig.update_layout(
        width=1000,
        height=600
               + (300 if missing_novel else 0)
               + (200+50*len(metrics) if table else 0),
        margin=dict(l=30, r=0, t=30, b=30),
        title=dict(xref="container", yref="container", yanchor="bottom"),
        xaxis7=dict(domain=[0.05, 0.95]),
        yaxis7=dict(
            tickmode='array',
            tickvals=(
                [-i/10 for i in range(1, 11)] + [i/10 for i in range(1, 11)]
            ),
            ticktext=[str(i/10) for i in range(1, 11)],
            zeroline=True,
            zerolinewidth=2,
            zerolinecolor='black',
        ),
    )
    return fig
