import random
import re
import string
import subprocess
from pathlib import Path

from pydantic import BaseModel

from ..struct import Annotation


class CompareMetrics(BaseModel):

    sensitivity: float
    precision: float


class AnnotationComparison(BaseModel):

    base: CompareMetrics
    exon: CompareMetrics
    intron: CompareMetrics
    intron_chain: CompareMetrics
    transcript: CompareMetrics
    locus: CompareMetrics


def compare_gtf(
    annotation: Annotation | Path | str,
    reference: Annotation | Path | str,
    gffcompare: Path | str | None = None,
) -> AnnotationComparison:
    """Compare two annotation with the tool gffcompare:
    https://github.com/gpertea/gffcompare

    The result is an easily accessible collection of metrics returned by
    this program.
    All files generated by gffcompare are immediately deleted after
    processing.

    Args:
        annotation (Annotation or Path): The annotation you want to
            compare to the reference. If an
            :class:`~bricks2marble.struct.annotation.Annotation` is
            given, this will be converted to a gtf file first with the
            `.to_gtf()` method.
        reference (Annotation or Path): The reference annotation. If an
            :class:`~bricks2marble.struct.annotation.Annotation` is
            given, this will be converted to a gtf file first with the
            `.to_gtf()` method.
        gffcompare (Path, optional): Path to the executable gffcompare.
            Defaults to just 'gffcompare', if it is properly added to
            the path.

    Returns:
        AnnotationComparison: See
            :class:`bricks2marble.tools.gtf.AnnotationComparison`.
    """
    if isinstance(annotation, str): annotation = Path(annotation)
    if isinstance(reference, str): reference = Path(reference)
    if isinstance(gffcompare, Path): gffcompare = str(gffcompare)
    if gffcompare is None: gffcompare = "gffcompare"

    random_id = "".join(
        random.choices(string.ascii_uppercase + string.digits, k=10)
    )
    cache_dir = Path.cwd() / f"_cache_{random_id}/"
    cache_dir.mkdir(exist_ok=True)

    generated: list[str] = []

    if isinstance(annotation, Annotation):
        annotation.to_gtf(cache_dir / "annotation.gtf")
        annotation = cache_dir / "annotation.gtf"
        generated.append(str(annotation))
    if isinstance(reference, Annotation):
        reference.to_gtf(cache_dir / "reference.gtf")
        reference = cache_dir / "reference.gtf"
        generated.append(str(reference))

    subprocess.run([
        f"{gffcompare}",
        "--strict-match",
        "-e 0",
        "-T",
        "-o",
        str(cache_dir) + ("/" if not str(cache_dir).endswith("/") else ""),
        "-r",
        str(reference),
        str(annotation),
    ], check=True)

    results = {}
    pattern = re.compile(r'^\s*(.+?) level:\s+([\d.]+)\s+\|\s+([\d.]+)')

    with open(cache_dir / ".stats", 'r', encoding='utf-8') as file:
        for line in file:
            match = pattern.match(line)
            if match:
                level = match.group(1).strip().lower().replace(" ", "_")
                sensitivity = float(match.group(2))
                precision = float(match.group(3))
                results[level] = {
                    'sensitivity': sensitivity,
                    'precision': precision
                }

    generated += [".annotated.gtf", ".loci", ".stats", ".tracking"]

    for name in generated:
        (cache_dir / name).unlink()
    if not any(cache_dir.iterdir()):
        cache_dir.rmdir()

    return AnnotationComparison(**results)
